### ISSUE TITLE
Login bug in v0.19.0

### ISSUE THREAD

**Issue by mpint** [stormpath/stormpath-sdk-node#590]
Hello,
I'm using express-stormpath and can log in fine when using stormpath-sdk v0.18.5, but I get a type error when I upgrade stormpath to v0.19.

Here's the cURL request that fails:

```
curl -X POST -H "Accept: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 28960460-ac48-ee95-9803-0079a9a04ef9" -H "Content-Type: application/x-www-form-urlencoded" -d 'username=<MY_USERNAME>&password=<MY_PASSWORD>' "http://localhost:4000/login"
```
Here's the stack trace:

```
TypeError: source.hasOwnProperty is not a function
    at /Users/michael/Code/web-auth/node_modules/stormpath/lib/utils.js:255:18
    at Array.forEach (native)
    at /Users/michael/Code/web-auth/node_modules/stormpath/lib/utils.js:254:25
    at Array.forEach (native)
    at Object.extend (/Users/michael/Code/web-auth/node_modules/stormpath/lib/utils.js:253:11)
    at OAuthPasswordGrantRequestAuthenticator.authenticate (/Users/michael/Code/web-auth/node_modules/stormpath/lib/oauth/password-grant.js:132:21)
    at continueWithAuthentication (/Users/michael/Code/web-auth/node_modules/express-stormpath/lib/helpers/authenticate.js:33:19)
    at /Users/michael/Code/web-auth/node_modules/express-stormpath/lib/helpers/authenticate.js:78:7
    at Config.exports.preLoginHandler (/Users/michael/Code/web-auth/lib/middleware/login.js:9:3)
```

**Comment by mdeggies** [comment]
Hi @mpint, can you clarify if you're using express-stormpath (which includes the default /login route) or stormpath (for Node) which does not? If you're using the Node SDK alone, can you please post your /login code? This will help us reproduce.

**Comment by mpint** [comment]
Yep, I'm using the express-stormpath login route and the exception is thrown before my postLoginHandler.  My project requires both express-stormpath and stormpath.

**Comment by mdeggies** [comment]
@mpint thanks! What version of express-stormpath are you using? I'm testing via [the example project](https://github.com/stormpath/express-stormpath-sample-project) and have express-stormpath ^3.x (specifically v3.1.6) and stormpath v0.19.0 (found via npm list). The account is returned with the following: 

`curl -X POST -H "Accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -H "Authorization: Basic $B64_ID:$B64_SECRET" -H "Postman-Token: b91767cb-9a89-99f9-adbd-8baaea98f228" -d 'login=$EMAIL&$PASSWORD' "http://localhost:3000/login"`

**Comment by mpint** [comment]
Hey @mdeggies, I can still reproduce the error with express-stormpath v3.1.8 and stormpath 0.19.0.  I'm running node v6.9.3.

**Comment by mdeggies** [comment]
Hmm. I just tested on 3.1.8 and still not seeing this error. Did you change the default /login route at all? Please send over a zip of your project to support@stormpath.com and I'll take a look.

**Comment by asargento** [comment]
Hello.
I have the same problem and I found that problem is due the req.body creation.
The problem is on utils.js line 255 (function extend).
And in this post is the explanation: 
http://stackoverflow.com/questions/16585209/node-js-object-object-has-no-method-hasownproperty

I am using node 6.9.1, express 4.14.0 and stormpath 0.19.1

**Comment by asargento** [comment]
More information about this issue.
The change of /lib/oauth/password-grant.js introducing on commit [ed15491](https://github.com/stormpath/stormpath-sdk-node/commit/ed15491c6015141c9731702db1c5a29e4e49bddb#diff-d6101d10a882423ac4e58a229d75ed21), line 132 is causing the problem.

**Comment by Tweety-FER** [comment]
@asargento Thanks a lot for all the information! This PR should resolve this issue.
@mdeggies Added a fix and an additional check, as well as some tests, so that it behaves correctly and more like underscore's or lodash's  `extend`.

**Comment by mgruel** [comment]
Is there a timeline, when the fix will be available in master?

**Comment by mdeggies** [comment]
Thanks @asargento! Feel free to email me (michele@stormpath.com) with your address, and I'll send you some swag for helping out :) 

@mgruel We'll update the status of the issue when it's in review, and again when it's merged. Sorry we don't have an ETA on this yet.

**Comment by robertjd** [comment]
Thanks everyone!  This fix is now available in release 0.19.2, can you please try this and let me know if the problem is resolved?

**Comment by mgruel** [comment]
@robertjd The problem is gone. 
@Tweety-FER Thanks for the fix.

**Comment by mgruel** [comment]
@Tweety-FER Thank you for the fix.
@robertjd I will check the fix, but from what i saw in npmjs, only the `stormpath` package was updated. The `express-stormpath` package, which references `stormpath` was not updated to use the new release.
